language: node_js
node_js:
  - "6"
  - "4"
env:
  - GRAPHQL_VERSION=0.6
  - GRAPHQL_VERSION=0.7
  - GRAPHQL_VERSION=0.8
install:
  # We need a new version of npm to install babel in such a way that mocha can
  # find it.
  - npm install -g npm@3
  - npm install graphql@${GRAPHQL_VERSION}
  - npm install
